// Nifty 100 Stock Symbols
export const NIFTY_100_SYMBOLS = [
  "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", 
  "AMBUJACEM", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", 
  "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "BANKBARODA", "BERGEPAINT", 
  "BHARTIARTL", "BIOCON", "BOSCHLTD", "BPCL", "BRITANNIA", "CHOLAFIN", 
  "CIPLA", "COALINDIA", "COLPAL", "DLF", "DMART", "DIVISLAB", "DRREDDY", 
  "EICHERMOT", "ETERNAL", "GAIL", "GODREJCP", "GRASIM", "HCLTECH", 
  "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", 
  "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIPRULI", "INDHOTEL", 
  "INDUSINDBK", "INFY", "IOC", "IRFC", "ITC", "JSWSTEEL", "KOTAKBANK", 
  "LT", "LTIM", "LICI", "MARUTI", "MAXFIN", "NAUKRI", "NESTLEIND", 
  "NTPC", "ONGC", "PIDILITIND", "POWERGRID", "RECLTD", "RELIANCE", 
  "SBILIFE", "SBIN", "SHREECEM", "SIEMENS", "SUNPHARMA", "TATAMOTORS", 
  "TATASTEEL", "TCS", "TECHM", "TITAN", "ULTRACEMCO", "VEDL", "WIPRO"
];

// Additional symbols from your list
export const ADDITIONAL_SYMBOLS = [
  "BANDHANBNK", "CANBK", "HDFCAMC", "MUTHOOTFIN", "PNB", "SBICARD", 
  "BEL", "BHARATFORG", "HAL", "HAVELLS", "HPCL", "IGL", "PETRONET", 
  "TATAPOWER", "INDIGO", "MAHINDRA", "TVSMOTOR", "GLAND", "LUPIN", 
  "TORNTPHARM", "ABCAPITAL", "DABUR", "JSPL", "PIRAMAL", "SRF", 
  "TATACONSUM", "TATACHEM", "UBL", "MCDOWELL-N", "VBL", "ZEEL", "UPL"
];

// Combined symbol list
export const ALL_SYMBOLS = [...NIFTY_100_SYMBOLS, ...ADDITIONAL_SYMBOLS];

// Exchange mappings
export const EXCHANGE_CODES = {
  NSE: '1',
  NFO: '2', 
  BSE: '3',
  BFO: '4'
} as const;

export const EXCHANGE_NAMES = {
  '1': 'NSE',
  '2': 'NFO',
  '3': 'BSE', 
  '4': 'BFO'
} as const;

// Time intervals
export const TIME_INTERVALS = [
  '5s', '15s', '30s', '1m', '5m', '15m', '30m', '60m'
] as const;

// Popular stock categories for easy access
export const STOCK_CATEGORIES = {
  BANKING: ['HDFCBANK', 'ICICIBANK', 'SBIN', 'AXISBANK', 'KOTAKBANK', 'INDUSINDBK', 'BANKBARODA'],
  IT: ['TCS', 'INFY', 'HCLTECH', 'WIPRO', 'TECHM', 'LTIM'],
  AUTO: ['MARUTI', 'TATAMOTORS', 'BAJAJ-AUTO', 'HEROMOTOCO', 'EICHERMOT', 'MAHINDRA'],
  PHARMA: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'DIVISLAB', 'BIOCON', 'LUPIN'],
  FMCG: ['HINDUNILVR', 'BRITANNIA', 'DABUR', 'GODREJCP', 'COLPAL', 'TATACONSUM'],
  ENERGY: ['RELIANCE', 'ONGC', 'BPCL', 'IOC', 'GAIL', 'COALINDIA'],
  METALS: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL'],
  TELECOM: ['BHARTIARTL'],
  CEMENT: ['ULTRACEMCO', 'SHREECEM', 'AMBUJACEM']
} as const;
